name: Upload WP theme from Artifact to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Upload Theme Artifact
        uses: actions/upload-artifact@v2
        with:
          name: wp-theme
          path: ./ocean-wp.zip
           
      - name: Download Theme Artifact
        uses: actions/download-artifact@v2
        with:
          name: wp-theme
      
      
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY}}
          port: 22
          source: /home/runner/work/TheWave-WP/TheWave-WP/ocean-wp.zip
          target: /var/www/html/wp-content/themes/


      - name: give perm on ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
              sudo chmod 777 -R /var/www/
              mv /var/www/html/wp-content/themes/github/workspace/ocean-wp.zip  /var/www/html/wp-content/themes/
              unzip ocean-wp.zip
               
  clean:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Delete the Theme Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: wp-theme
